# Generated by Django 4.2.6 on 2023-10-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=70)),
                ('stuname', models.CharField(max_length=110)),
                ('stuemail', models.CharField(max_length=110)),
                ('stupass', models.CharField(max_length=110)),
            ],
        ),
    ]
